task: CLASSIFICATION
language_sensitive: false
routes:
  -
    task_alias: classification
    metric: accuracy
    pipeline_id: classification.any.accuracy.classify_v1
    nodes:
      - scoring/classify
    input_contract: scoring/classify
    executor: sure_eval.evaluation.tasks.classification.pipeline.evaluate_classification_files
  -
    task_alias: SER
    metric: accuracy
    pipeline_id: ser.any.accuracy.classify_v1
    nodes:
      - scoring/classify
    input_contract: scoring/classify
    executor: sure_eval.evaluation.tasks.classification.pipeline.evaluate_classification_files
  -
    task_alias: GR
    metric: accuracy
    pipeline_id: gr.any.accuracy.classify_v1
    nodes:
      - scoring/classify
    input_contract: scoring/classify
    executor: sure_eval.evaluation.tasks.classification.pipeline.evaluate_classification_files
