task: SD
language_sensitive: false
routes:
  -
    metric: der
    pipeline_id: sd.any.der.meeteval_v1
    nodes:
      - scoring/meeteval
    input_contract: scoring/meeteval
    executor: sure_eval.evaluation.tasks.sd.pipeline.evaluate_sd_files
    params:
      collar: 0.25
